### PR TITLE
Fix URN hashCode implementation

### LINKED ISSUE #15: Invalid URN hashCode implementation
According to the [Java specification for hashCode](https://docs.oracle.com/javase/8/docs/api/java/lang/Object.html#hashCode--):

> If two objects are equal according to the equals(Object) method, then calling the hashCode method on each of the two objects must produce the same integer result. 

This true for `URN_2141` objects but not for `URN_8141` objects. Indeed, the two following URNs are equal but produce different `hashCode`s:
```
URN.rfc8141().parse("urn:example:foo-bar-baz-qux?+CCResolve:cc=uk?=op=map#somepart"); 
URN.rfc8141().parse("urn:example:foo-bar-baz-qux");
```
This is due to the fact that `hashCode`, which calls `toString` in the current implementation, takes the RQF components into account, whereas `equals` does not.

According to [RFC 8141](https://tools.ietf.org/html/rfc8141), RQF components should not be taken into account for URN-equivalence, so I suggest changing `hashCode's implementation to reflect this. We're happy to contribute this fix! 👍

### PR DESCRIPTION
**Pull request by PyvesB**
Fixes  #15. I used a "Java 7 style" `hashCode` and strengthened one of the existing unit tests.

### CODE REVIEW

File: src/main/java/de/slub/urn/URN.java [hunk 1]
```diff
@@ -89,7 +90,7 @@ public URI toURI() throws URISyntaxException {
      */
     @Override
     public int hashCode() {
-        return this.toString().hashCode();
+        return Objects.hash(namespaceIdentifier(), namespaceSpecificString(), supportedRFC());
```
Comment (claussni) [inline src/main/java/de/slub/urn/URN.java]: I didn't know about Objects.hash() until now. Thank you!
